name: "Build testing"
on: [push, pull_request]

jobs:
  macos-build:
    strategy:
      matrix:
        os: [macos-10.15]
        cc: [clang]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      # Needed since default behavior is to only fetch the most recent commit, which results in r1 always being built
        with:
          fetch-depth: 0
      - name: Install dependencies
        shell: bash
        run: |
          brew install scons
          curl -LJO https://github.com/pokemon-speedrunning/gsr-qt-builds/releases/download/v5.15.0-gsr/Qt-5.15.0-macos-clang.7z
          sudo 7z x Qt-5.15.0-macos-clang.7z -o/usr/local/
      - name: Build
        shell: bash
        run: |
          echo 'export PATH="/usr/local/Qt-5.15.0/bin:$PATH"' >> ~/.bash_profile
          source ~/.bash_profile
          sh ./scripts/build_shlib.sh
          sh ./scripts/build_qt.sh
          (cd ./gambatte_qt/bin && macdeployqt Gambatte-Speedrun.app -dmg)
      - name: Upload .dmg
        uses: actions/upload-artifact@v2
        with:
          name: Gambatte-Speedrun.dmg
          path: ./gambatte_qt/bin/Gambatte-Speedrun.dmg
      - name: Upload .dylib
        uses: actions/upload-artifact@v2
        with:
          name: libgambatte.dylib
          path: ./libgambatte/libgambatte.dylib

  msvc-build:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      # Needed since default behavior is to only fetch the most recent commit, which results in r1 always being built
        with:
          fetch-depth: 0
      # Easier way to set up the Developer Command Prompt for VS 2019?
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      - name: Install dependencies
        run: |
          pip install scons
          curl -LJO https://github.com/pokemon-speedrunning/gsr-qt-builds/releases/download/v5.15.0-gsr/Qt-5.15.0-win32-msvc.7z
          7z x Qt-5.15.0-win32-msvc.7z -oC:\Qt
      - name: Build
        run: |
          set PATH=C:\Qt\Qt-5.15.0\bin;%PATH%
          msvc\build_qt.bat
      - name: Upload .exe (32-bit)
        uses: actions/upload-artifact@v2
        with:
          name: gambatte_speedrun.exe
          path: ./gambatte_qt/bin/gambatte_speedrun.exe

  # Installing Qt from the MinGW repos takes a while, so only build shared library
  #  - MinGW 64-bit .dll slightly outperformed the MSVC one in some initial testing, so upload that as artifact
  #  - If prebuilt MinGW binaries are added to gsr-qt-builds, we can re-add building the executable(s)
  mingw-build:
    strategy:
      matrix:
        mingw: ["MINGW64"]
        include:
          - mingw: "MINGW64"
            package: "mingw-w64-x86_64"
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      # Needed since default behavior is to only fetch the most recent commit, which results in r1 always being built
        with:
          fetch-depth: 0
      # Easier way to set up the MinGW shell?
      - name: Set up mingw64 shell (1)
        shell: pwsh
        run: |
          echo ::add-path::C:\msys64\usr\bin\
      - name: Set up mingw64 shell (2)
        run: |
          echo "(idk why this is needed)"
        shell: bash.exe --login -eo pipefail "{0}"
      - name: Build
        shell: bash
        run: |
          echo 'PATH="/mingw64/bin:${PATH}"' >> ~/.bash_profile
          source ~/.bash_profile
          sh ./scripts/build_shlib.sh
      - name: Upload .dll (64-bit)
        uses: actions/upload-artifact@v2
        with:
          name: libgambatte.dll
          path: ./libgambatte/libgambatte.dll

  # Test that things build fine on Ubuntu (don't upload artifacts; Linux users should build on their own)
  ubuntu-build:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        cc: [gcc]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get -qq update
          sudo apt-get install scons qt5-default libqt5x11extras5-dev libxrandr-dev libxv-dev libasound2-dev
      - name: Build
        shell: bash
        run: |
          sh ./scripts/build_shlib.sh
          sh ./scripts/build_qt.sh
